version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: appcd-subprocess
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: appcd-gulp
    versions:
    - 3.1.3
    - 3.1.4
    - 3.1.5
  - dependency-name: appcd-logger
    versions:
    - 3.0.4
    - 3.0.5
    - 3.0.6
  - dependency-name: appcd-fs
    versions:
    - 2.0.4
    - 2.0.5
    - 2.0.6
  - dependency-name: appcd-path
    versions:
    - 2.0.5
    - 2.0.6
    - 2.0.7
